- job:
    name: gate-ci-puppet-syntax
    node: precise

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - puppet-syntax
      - pyflakes

    publishers:
      - console-log


- job:
    name: gate-ci-puppet-lint
    node: precise

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - shell: "rake lint"

    publishers:
      - console-log


- job:
    name: ci-puppet-compare-xml
    node: precise

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - shell: "./tools/run-compare-xml.sh"

    publishers:
      - console-log



